version: '3.8'

services:
  promptguard-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deberta-promptguard
    ports:
      - "5158:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Logging__MaxLogSize=1000
      - ModelConfiguration__ModelPath=/app/models/model.onnx
      - ModelConfiguration__TokenizerPath=/app/models/tokenizer.json
    volumes:
      # Mount models directory from host (if models are too large for image)
      - ./models:/app/models:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - promptguard-network

networks:
  promptguard-network:
    driver: bridge


